### PR TITLE
Fix #19: Requested feature: Ability to collect all distinct values for a given node/path

### LINKED ISSUE #19: Requested feature: Ability to collect all distinct values for a given node/path
idea would be that after you have your tree you could do something like

`tree.scanForDistinctValuesAtPath(path)`
or `node.scanForDistinctValues()`

which would hold in memory against that node in the tree, the list of possible values.

(implies you can get it later e.g. 
`node.getFoundValues()`
or `tree.getFoundValuesAtPath(path)`

Nice to have:

- features/examples scripts to view the lists of found values for different node paths in human friendly table, like you did with descriptions. 

There are follow on feature ideas from this, but I will put them in separate tickets and link back to this one.

A few further notes:
- this should remove duplicates, so you only collect distinct values
- maybe alpha sort values for convenience?
- keep case of text exactly as found
- don't limit this to recurring values, find everything but maybe have a way to distinguish recurring values from one-off values? 
- There are two motivations for collecting found values:
  (i) to help us enumerate the closed set of possible values for a given field.
  (ii) to collect sample data for use in mockups, visualisations etc.
  At this stage, I don't think we need to differentiate between them, though to achieve the abilities of cutting / separating them these issues become important:
     - #21
     - #22
     - #23

### PR DESCRIPTION
**Pull request by Amustache**
Alright @alexbfree I finished that feature, and I think I have a lot of things that I can improve (cf. #40 for instance), but it is already working. Before going further, would you kindly review it?

It works basically like this:

```python
import json
from argonodes.nodes import Tree
from argonodes.applies import DistinctValues

json_data = ...  # Your raw data in JSON format
tree = Tree(json_data)

distinctvalues = DistinctValues()
tree.apply(distinctvalues)
```

or

```python
distinctvalues = DistinctValues()
distinctvalues(tree)
```

And now, the `distinctvalues` object is holding every distinct values, can be used to explore and tag them, and can be expanded to add more sorcelery to the process.

More:

```python
...  # previous steps
all_as_dict = distinctvalues.data
all_values = distinctvalues.get_found_values()
recurring_values_only = distinctvalues.get_recurring_values()
liste = distinctvalues.to_list()
```

Result example (`distinctvalues.data`):

```json
{
   "$":{
      "description":"",
      "children":{
         "$.timelineObjects":1
      },
      "data":{}
   },
   "$.timelineObjects":{
      "description":"",
      "children":{
         "$.timelineObjects[*]":77
      },
      "data":{}
   },
   "$.timelineObjects[*].placeVisit.placeConfidence":{
      "description":"",
      "children":{},
      "data":{
         "HIGH_CONFIDENCE":19,
         "MEDIUM_CONFIDENCE":14,
         "LOW_CONFIDENCE":3,
         "USER_CONFIRMED":2
      }
   }
}
```

Before going further, I'll let you take a look!

### CODE REVIEW

**Review by alexbfree — APPROVED** [review]
I have not done a detailed code review but the description in the PR seems to meet the requirements, and the code changes look good/clean, easy to read & maintain.

Can we make sure that the usages of the tool get added to a README or similar if they are not already?

**Comment by alexbfree** [comment]
i've just been testing this and couldn't get the import to work (I git cloned latest code)

Screenshot 2022-06-06 at 16 40 00

**Comment by Amustache** [comment]
> i've just been testing this and couldn't get the import to work (I git cloned latest code)
> 
> Screenshot 2022-06-06 at 16 40 00

`from argonodes.appliers import DistinctValues` *

I believe I forgot to edit the Wiki, it is now done.

**Comment by Amustache** [comment]
@alexbfree 

> i've just been testing this and couldn't get the import to work (I git cloned latest code)
> 
> Screenshot 2022-06-06 at 16 40 00

`from argonodes.appliers import DistinctValues` *

I believe I forgot to edit the Wiki, it is now done.

**Pull request merged**
